manifest:
  remotes:
    - name: zmk-urob
      url-base: https://github.com/romones
  projects:
    - name: zmk-urob
      remote: zmk-urob
      revision: main
      import: app/west.yml
  self:
    path: config
